version: '3.9'

services:
  app:
    container_name: 'app_english_test'
    restart: always
    image: romanv79/englishtest:v1.0.11
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASS: ${ADMIN_PASS}

    depends_on:
      - postgres

  postgres:
    container_name: 'postgres'
    restart: always
    image: 'postgres:16.0'
    environment:
      SPRING_PROFILES_ACTIVE: prod
      POSTGRES_DB: english
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata:
    name: 'app_pgdata'