services:
  postgres:
    image: 'postgres:16.0'
    environment:
      SPRING_PROFILES_ACTIVE: ide
      POSTGRES_DB: english
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
    ports:
      - '5432:5432'
